R Packages to install from CRAN and Bioconductor: Type into R studio command line.
install.packages("shiny")
install.packages("shinyBS")
install.packages("shinythemes")
install.packages("shinydashboard")
install.packages("extRemes")
install.packages("ggplot2")
install.packages("glmpath")
install.packages("lme4")
install.packages("mediation")
install.packages("NMF")
install.packages("plotly")
install.packages("reshape")
install.packages("reshape2")
install.packages("SNFtool")
install.packages("devtools")
install.packages("survival")
install.packages("reticulate")
install.packages("icluster")
install.packages("RColorBrewer")
if (!requireNamespace("BiocManager"))
install.packages("BiocManager")
BiocManager::install()
BiocManager::install("CancerSubtypes", version = "3.8")
BiocManager::install("omicade4", version = "3.8")
devtools::install_github("bioFAM/MOFA")
BiocManager::install("iClusterPlus", version = "3.8")

